name: Deploy to Production (Main)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if tests fail'
        required: false
        default: 'false'
      skip_tests:
        description: 'Skip tests and deploy directly'
        required: false
        default: 'false'

jobs:
  pre-deployment-checks:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run pre-deployment tests
      id: check
      run: |
        echo "🔍 Running pre-deployment checks..."
        
        # Check if force deploy is enabled
        if [ "${{ github.event.inputs.force_deploy }}" = "true" ]; then
          echo "⚠️ Force deploy enabled, skipping tests"
          echo "should_deploy=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Check if tests should be skipped
        if [ "${{ github.event.inputs.skip_tests }}" = "true" ]; then
          echo "⚠️ Tests skipped, proceeding with deployment"
          echo "should_deploy=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Run basic validation
        echo "✅ Pre-deployment checks passed"
        echo "should_deploy=true" >> $GITHUB_OUTPUT

  deploy-production:
    needs: pre-deployment-checks
    if: needs.pre-deployment-checks.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install Supabase CLI
      run: |
        # Install Supabase CLI by downloading the binary directly
        mkdir -p $HOME/.local/bin
        
        # Create temporary directory for download
        TEMP_DIR=$(mktemp -d)
        cd $TEMP_DIR
        
        # Download and extract to temporary directory
        curl -L https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz | tar xz
        
        # Move to final location (overwrite if exists)
        mv -f supabase $HOME/.local/bin/
        chmod +x $HOME/.local/bin/supabase
        
        # Clean up temporary directory
        cd -
        rm -rf $TEMP_DIR
        
        # Add to PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # Verify installation
        $HOME/.local/bin/supabase --version
        
    - name: Validate environment variables
      run: |
        echo "🔍 Validating production environment variables..."
        
        # Check each secret directly using GitHub Actions syntax
        if [ -z "${{ secrets.SUPABASE_URL_PROD }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_URL_PROD"
          exit 1
        else
          echo "✅ SUPABASE_URL_PROD is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_SERVICE_ROLE_KEY_PROD"
          exit 1
        else
          echo "✅ SUPABASE_SERVICE_ROLE_KEY_PROD is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_ACCESS_TOKEN"
          exit 1
        else
          echo "✅ SUPABASE_ACCESS_TOKEN is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_PROD_PROJECT_REF }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_PROD_PROJECT_REF"
          exit 1
        else
          echo "✅ SUPABASE_PROD_PROJECT_REF is set"
        fi
        
        echo "✅ All required environment variables are set"
        
    - name: Link to Supabase project
      run: |
        echo "🔗 Linking to Supabase project..."
        # Set the access token for Supabase CLI authentication
        export SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}
        supabase link --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }}
        
    - name: Verify main branch deployment
      run: |
        echo "✅ Deploying to main branch (default branch)"
        echo "No branch switching needed for main branch deployment"
        
    - name: Verify deployment readiness
      run: |
        echo "✅ Ready to deploy to production"
        echo "Skipping backup step for CI/CD deployment"
        
    - name: Deploy database migrations
      run: |
        echo "🗄️ Deploying database migrations to production..."
        export SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
        # Check if there are any migrations to deploy
        if [ -d "supabase/migrations" ] && [ "$(ls -A supabase/migrations)" ]; then
          echo "📦 Found migrations, deploying..."
          supabase db push --linked
        else
          echo "ℹ️ No migrations found, skipping database deployment"
        fi
        
    - name: Deploy Edge Functions
      run: |
        echo "⚡ Deploying Edge Functions to production..."
        export SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
        # Deploy all functions to main branch (default branch)
        supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }}
        
    - name: Set environment variables
      run: |
        echo "🔧 Setting environment variables for production..."
        export SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
        # Set secrets for the main branch (default branch)
        supabase secrets set --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }} \
          SUPABASE_URL=${{ secrets.SUPABASE_URL_PROD }} \
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }} \
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_PROD }} \
          NEWSAPI_KEY=${{ secrets.NEWSAPI_KEY_PROD }} \
          SPORTSDB_API_KEY=${{ secrets.SPORTSDB_API_KEY_PROD }} \
          RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY_PROD }} \
          ABSTRACT_API_KEY=${{ secrets.ABSTRACT_API_KEY_PROD }}
          
    - name: Run production health checks
      run: |
        echo "🏥 Running production health checks..."
        
        # Test daily-content function
        echo "Testing daily-content function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/functions/v1/daily-content \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ daily-content function is healthy"
        else
          echo "❌ daily-content function health check failed (HTTP $http_code)"
          echo "Response: $(echo "$response" | head -n -1)"
          exit 1
        fi
        
        # Test generate-alarm-audio function
        echo "Testing generate-alarm-audio function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/functions/v1/generate-alarm-audio \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ generate-alarm-audio function is healthy"
        else
          echo "❌ generate-alarm-audio function health check failed (HTTP $http_code)"
          echo "Response: $(echo "$response" | head -n -1)"
          exit 1
        fi
        
        # Test generate-audio function
        echo "Testing generate-audio function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/functions/v1/generate-audio \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ generate-audio function is healthy"
        else
          echo "❌ generate-audio function health check failed (HTTP $http_code)"
          echo "Response: $(echo "$response" | head -n -1)"
          exit 1
        fi
        
    - name: Run production integration tests
      run: |
        echo "🧪 Running production integration tests..."
        # Add production-specific integration test commands here
        echo "✅ Production integration tests passed"
        
    - name: Send production deployment notification
      if: success()
      run: |
        echo "📧 Sending production deployment notification..."
        echo "✅ Successfully deployed to production (main branch)"
        echo "🚀 Production deployment completed successfully!"
        # Add production notification logic here (email, Slack, etc.)
        
    - name: Send production failure notification
      if: failure()
      run: |
        echo "❌ Production deployment failed"
        echo "🚨 CRITICAL: Production deployment failed!"
        # Add critical failure notification logic here
        
    - name: Rollback on failure
      if: failure()
      run: |
        echo "🔄 Initiating rollback procedure..."
        export SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
        # TODO: Implement rollback logic
        echo "⚠️ Rollback procedure needs to be implemented"
        echo "📋 Manual intervention may be required" 