name: Deploy to Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if tests fail'
        required: false
        default: 'false'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install Supabase CLI
      run: |
        echo "⚠️ Skipping Supabase CLI install - handled by Supabase GitHub integration"
        
    - name: Validate environment variables
      run: |
        echo "🔍 Validating development environment variables..."
        
        # Check each secret directly using GitHub Actions syntax
        if [ -z "${{ secrets.SUPABASE_URL_DEV }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_URL_DEV"
          exit 1
        else
          echo "✅ SUPABASE_URL_DEV is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY_DEV }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_SERVICE_ROLE_KEY_DEV"
          exit 1
        else
          echo "✅ SUPABASE_SERVICE_ROLE_KEY_DEV is set"
        fi
        
        if [ -z "${{ secrets.OPENAI_API_KEY_DEV }}" ]; then
          echo "❌ Missing required environment variable: OPENAI_API_KEY_DEV"
          exit 1
        else
          echo "✅ OPENAI_API_KEY_DEV is set"
        fi
        
        if [ -z "${{ secrets.NEWSAPI_KEY_DEV }}" ]; then
          echo "❌ Missing required environment variable: NEWSAPI_KEY_DEV"
          exit 1
        else
          echo "✅ NEWSAPI_KEY_DEV is set"
        fi
        
        if [ -z "${{ secrets.SPORTSDB_API_KEY_DEV }}" ]; then
          echo "❌ Missing required environment variable: SPORTSDB_API_KEY_DEV"
          exit 1
        else
          echo "✅ SPORTSDB_API_KEY_DEV is set"
        fi
        
        if [ -z "${{ secrets.RAPIDAPI_KEY_DEV }}" ]; then
          echo "❌ Missing required environment variable: RAPIDAPI_KEY_DEV"
          exit 1
        else
          echo "✅ RAPIDAPI_KEY_DEV is set"
        fi
        
        if [ -z "${{ secrets.ABSTRACT_API_KEY_DEV }}" ]; then
          echo "❌ Missing required environment variable: ABSTRACT_API_KEY_DEV"
          exit 1
        else
          echo "✅ ABSTRACT_API_KEY_DEV is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_DEV_PROJECT_REF }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_DEV_PROJECT_REF"
          exit 1
        else
          echo "✅ SUPABASE_DEV_PROJECT_REF is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_ACCESS_TOKEN"
          exit 1
        else
          echo "✅ SUPABASE_ACCESS_TOKEN is set"
        fi
        
        echo "✅ All required environment variables are set"
        
    - name: Link to development project
      run: |
        echo "⚠️ Skipping project link - handled by Supabase GitHub integration"
        
    - name: Deploy database migrations
      run: |
        echo "⚠️ Skipping database migrations - handled by Supabase GitHub integration"
        
    - name: Deploy Edge Functions
      run: |
        echo "⚠️ Skipping Edge Functions deploy - handled by Supabase GitHub integration"
        
    - name: Set environment variables
      run: |
        echo "⚠️ Skipping environment variable set - handled by Supabase GitHub integration"
          
    - name: Run health checks
      run: |
        echo "🏥 Running health checks..."
        
        # Test daily-content function
        echo "Testing daily-content function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_DEV }}/functions/v1/daily-content \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_DEV }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ daily-content function is healthy"
        else
          echo "❌ daily-content function health check failed (HTTP $http_code)"
          exit 1
        fi
        
        # Test generate-alarm-audio function
        echo "Testing generate-alarm-audio function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_DEV }}/functions/v1/generate-alarm-audio \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_DEV }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ generate-alarm-audio function is healthy"
        else
          echo "❌ generate-alarm-audio function health check failed (HTTP $http_code)"
          exit 1
        fi
        
    - name: Run integration tests
      run: |
        echo "🧪 Running integration tests..."
        # Add integration test commands here
        echo "✅ Integration tests passed"
        
    - name: Send deployment notification
      if: success()
      run: |
        echo "📧 Sending deployment notification..."
        # Add notification logic here (email, Slack, etc.)
        echo "✅ Development deployment completed successfully!"
        
    - name: Send failure notification
      if: failure()
      run: |
        echo "📧 Sending failure notification..."
        # Add failure notification logic here
        echo "❌ Development deployment failed!" 