name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if tests fail'
        required: false
        default: 'false'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install Supabase CLI
      run: |
        # Install Supabase CLI by downloading the binary directly
        mkdir -p $HOME/.local/bin
        
        # Create temporary directory for download
        TEMP_DIR=$(mktemp -d)
        cd $TEMP_DIR
        
        # Download and extract to temporary directory
        curl -L https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz | tar xz
        
        # Move to final location (overwrite if exists)
        mv -f supabase $HOME/.local/bin/
        chmod +x $HOME/.local/bin/supabase
        
        # Clean up temporary directory
        cd -
        rm -rf $TEMP_DIR
        
        # Add to PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # Verify installation
        $HOME/.local/bin/supabase --version
        
    - name: Validate environment variables
      run: |
        echo "🔍 Validating production environment variables..."
        
        # Check each secret directly
        if [ -z "${{ secrets.SUPABASE_URL_PROD }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_URL_PROD"
          exit 1
        else
          echo "✅ SUPABASE_URL_PROD is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_SERVICE_ROLE_KEY_PROD"
          exit 1
        else
          echo "✅ SUPABASE_SERVICE_ROLE_KEY_PROD is set"
        fi
        
        if [ -z "${{ secrets.OPENAI_API_KEY_PROD }}" ]; then
          echo "❌ Missing required environment variable: OPENAI_API_KEY_PROD"
          exit 1
        else
          echo "✅ OPENAI_API_KEY_PROD is set"
        fi
        
        if [ -z "${{ secrets.NEWSAPI_KEY_PROD }}" ]; then
          echo "❌ Missing required environment variable: NEWSAPI_KEY_PROD"
          exit 1
        else
          echo "✅ NEWSAPI_KEY_PROD is set"
        fi
        
        if [ -z "${{ secrets.SPORTSDB_API_KEY_PROD }}" ]; then
          echo "❌ Missing required environment variable: SPORTSDB_API_KEY_PROD"
          exit 1
        else
          echo "✅ SPORTSDB_API_KEY_PROD is set"
        fi
        
        if [ -z "${{ secrets.RAPIDAPI_KEY_PROD }}" ]; then
          echo "❌ Missing required environment variable: RAPIDAPI_KEY_PROD"
          exit 1
        else
          echo "✅ RAPIDAPI_KEY_PROD is set"
        fi
        
        if [ -z "${{ secrets.ABSTRACT_API_KEY_PROD }}" ]; then
          echo "❌ Missing required environment variable: ABSTRACT_API_KEY_PROD"
          exit 1
        else
          echo "✅ ABSTRACT_API_KEY_PROD is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_PROD_PROJECT_REF }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_PROD_PROJECT_REF"
          exit 1
        else
          echo "✅ SUPABASE_PROD_PROJECT_REF is set"
        fi
        
        if [ -z "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ]; then
          echo "❌ Missing required environment variable: SUPABASE_ACCESS_TOKEN"
          exit 1
        else
          echo "✅ SUPABASE_ACCESS_TOKEN is set"
        fi
        
        echo "✅ All required environment variables are set"
        
    - name: Link to production project
      run: |
        echo "🔗 Linking to production Supabase project..."
        # Set the access token for Supabase CLI authentication
        export SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}
        supabase link --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }}
        
    - name: Create backup
      run: |
        echo "💾 Creating database backup..."
        # Create a backup before deployment
        timestamp=$(date +"%Y%m%d_%H%M%S")
        echo "Backup timestamp: $timestamp"
        # Note: Actual backup would be done via Supabase dashboard or CLI
        
    - name: Deploy database migrations
      run: |
        echo "🗄️ Deploying database migrations..."
        # The project is already linked, so we can push directly
        supabase db push --linked
        
    - name: Deploy Edge Functions
      run: |
        echo "⚡ Deploying Edge Functions..."
        supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }}
        
    - name: Set environment variables
      run: |
        echo "🔧 Setting environment variables..."
        supabase secrets set --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }} \
          SUPABASE_URL=${{ secrets.SUPABASE_URL_PROD }} \
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }} \
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_PROD }} \
          NEWSAPI_KEY=${{ secrets.NEWSAPI_KEY_PROD }} \
          SPORTSDB_API_KEY=${{ secrets.SPORTSDB_API_KEY_PROD }} \
          RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY_PROD }} \
          ABSTRACT_API_KEY=${{ secrets.ABSTRACT_API_KEY_PROD }}
          
    - name: Run health checks
      run: |
        echo "🏥 Running health checks..."
        
        # Test daily-content function
        echo "Testing daily-content function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/functions/v1/daily-content \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ daily-content function is healthy"
        else
          echo "❌ daily-content function health check failed (HTTP $http_code)"
          exit 1
        fi
        
        # Test generate-alarm-audio function
        echo "Testing generate-alarm-audio function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/functions/v1/generate-alarm-audio \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ generate-alarm-audio function is healthy"
        else
          echo "❌ generate-alarm-audio function health check failed (HTTP $http_code)"
          exit 1
        fi
        
        # Test database connectivity
        echo "Testing database connectivity..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/rest/v1/users?select=count \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ Database connectivity is healthy"
        else
          echo "❌ Database connectivity check failed (HTTP $http_code)"
          exit 1
        fi
        
    - name: Run production tests
      run: |
        echo "🧪 Running production tests..."
        # Add production-specific test commands here
        echo "✅ Production tests passed"
        
    - name: Send deployment notification
      if: success()
      run: |
        echo "📧 Sending deployment notification..."
        # Add notification logic here (email, Slack, etc.)
        echo "✅ Production deployment completed successfully!"
        
    - name: Send failure notification
      if: failure()
      run: |
        echo "📧 Sending failure notification..."
        # Add failure notification logic here
        echo "❌ Production deployment failed!"
        
    - name: Rollback on failure
      if: failure()
      run: |
        echo "🔄 Initiating rollback..."
        # Add rollback logic here
        echo "⚠️ Manual rollback may be required" 