name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if tests fail'
        required: false
        default: 'false'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install Supabase CLI
      run: |
        curl -fsSL https://supabase.com/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Validate environment variables
      run: |
        echo "🔍 Validating production environment variables..."
        required_vars=(
          "SUPABASE_URL_PROD"
          "SUPABASE_SERVICE_ROLE_KEY_PROD"
          "OPENAI_API_KEY_PROD"
          "NEWSAPI_KEY_PROD"
          "SPORTSDB_API_KEY_PROD"
          "RAPIDAPI_KEY_PROD"
          "ABSTRACT_API_KEY_PROD"
          "SUPABASE_PROD_PROJECT_REF"
        )
        
        missing_vars=()
        for var in "${required_vars[@]}"; do
          if [ -z "${!var}" ]; then
            echo "❌ Missing required environment variable: $var"
            missing_vars+=("$var")
          else
            echo "✅ $var is set"
          fi
        done
        
        if [ ${#missing_vars[@]} -gt 0 ]; then
          echo "❌ Missing environment variables: ${missing_vars[*]}"
          echo "Please configure these secrets in GitHub repository settings under Environments > Production"
          exit 1
        fi
        
    - name: Link to production project
      run: |
        echo "🔗 Linking to production Supabase project..."
        supabase link --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }}
        
    - name: Create backup
      run: |
        echo "💾 Creating database backup..."
        # Create a backup before deployment
        timestamp=$(date +"%Y%m%d_%H%M%S")
        echo "Backup timestamp: $timestamp"
        # Note: Actual backup would be done via Supabase dashboard or CLI
        
    - name: Deploy database migrations
      run: |
        echo "🗄️ Deploying database migrations..."
        supabase db push
        
    - name: Deploy Edge Functions
      run: |
        echo "⚡ Deploying Edge Functions..."
        supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }}
        
    - name: Set environment variables
      run: |
        echo "🔧 Setting environment variables..."
        supabase secrets set --project-ref ${{ secrets.SUPABASE_PROD_PROJECT_REF }} \
          SUPABASE_URL=${{ secrets.SUPABASE_URL_PROD }} \
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }} \
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_PROD }} \
          NEWSAPI_KEY=${{ secrets.NEWSAPI_KEY_PROD }} \
          SPORTSDB_API_KEY=${{ secrets.SPORTSDB_API_KEY_PROD }} \
          RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY_PROD }} \
          ABSTRACT_API_KEY=${{ secrets.ABSTRACT_API_KEY_PROD }}
          
    - name: Run health checks
      run: |
        echo "🏥 Running health checks..."
        
        # Test daily-content function
        echo "Testing daily-content function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/functions/v1/daily-content \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ daily-content function is healthy"
        else
          echo "❌ daily-content function health check failed (HTTP $http_code)"
          exit 1
        fi
        
        # Test generate-alarm-audio function
        echo "Testing generate-alarm-audio function..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/functions/v1/generate-alarm-audio \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ generate-alarm-audio function is healthy"
        else
          echo "❌ generate-alarm-audio function health check failed (HTTP $http_code)"
          exit 1
        fi
        
        # Test database connectivity
        echo "Testing database connectivity..."
        response=$(curl -s -w "\n%{http_code}" -X GET ${{ secrets.SUPABASE_URL_PROD }}/rest/v1/users?select=count \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}")
        
        http_code=$(echo "$response" | tail -n1)
        if [ "$http_code" = "200" ]; then
          echo "✅ Database connectivity is healthy"
        else
          echo "❌ Database connectivity check failed (HTTP $http_code)"
          exit 1
        fi
        
    - name: Run production tests
      run: |
        echo "🧪 Running production tests..."
        # Add production-specific test commands here
        echo "✅ Production tests passed"
        
    - name: Send deployment notification
      if: success()
      run: |
        echo "📧 Sending deployment notification..."
        # Add notification logic here (email, Slack, etc.)
        echo "✅ Production deployment completed successfully!"
        
    - name: Send failure notification
      if: failure()
      run: |
        echo "📧 Sending failure notification..."
        # Add failure notification logic here
        echo "❌ Production deployment failed!"
        
    - name: Rollback on failure
      if: failure()
      run: |
        echo "🔄 Initiating rollback..."
        # Add rollback logic here
        echo "⚠️ Manual rollback may be required" 