name: Test Environment Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Test secret access
      run: |
        echo "Testing direct secret access:"
        echo "SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD }}"
        echo "SUPABASE_SERVICE_ROLE_KEY_PROD: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD }}"
        echo "OPENAI_API_KEY_PROD: ${{ secrets.OPENAI_API_KEY_PROD }}"
        echo "NEWSAPI_KEY_PROD: ${{ secrets.NEWSAPI_KEY_PROD }}"
        echo "SPORTSDB_API_KEY_PROD: ${{ secrets.SPORTSDB_API_KEY_PROD }}"
        echo "RAPIDAPI_KEY_PROD: ${{ secrets.RAPIDAPI_KEY_PROD }}"
        echo "ABSTRACT_API_KEY_PROD: ${{ secrets.ABSTRACT_API_KEY_PROD }}"
        echo "SUPABASE_PROD_PROJECT_REF: ${{ secrets.SUPABASE_PROD_PROJECT_REF }}"
        
    - name: Test shell variable expansion
      run: |
        echo "Testing shell variable expansion:"
        required_vars=(
          "SUPABASE_URL_PROD"
          "SUPABASE_SERVICE_ROLE_KEY_PROD"
          "OPENAI_API_KEY_PROD"
          "NEWSAPI_KEY_PROD"
          "SPORTSDB_API_KEY_PROD"
          "RAPIDAPI_KEY_PROD"
          "ABSTRACT_API_KEY_PROD"
          "SUPABASE_PROD_PROJECT_REF"
        )
        
        for var in "${required_vars[@]}"; do
          if [ -z "${!var}" ]; then
            echo "❌ Missing: $var"
          else
            echo "✅ Found: $var"
          fi
        done 