name: Test Secrets Configuration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - development

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Test Environment Variables
      run: |
        echo "🔍 Testing ${{ github.event.inputs.environment }} environment variables..."
        
        # List all available secrets (without exposing values)
        echo "Available secrets:"
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD != '' && 'SET' || 'NOT SET' }}"
          echo "SUPABASE_SERVICE_ROLE_KEY_PROD: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_PROD != '' && 'SET' || 'NOT SET' }}"
          echo "OPENAI_API_KEY_PROD: ${{ secrets.OPENAI_API_KEY_PROD != '' && 'SET' || 'NOT SET' }}"
          echo "NEWSAPI_KEY_PROD: ${{ secrets.NEWSAPI_KEY_PROD != '' && 'SET' || 'NOT SET' }}"
          echo "SPORTSDB_API_KEY_PROD: ${{ secrets.SPORTSDB_API_KEY_PROD != '' && 'SET' || 'NOT SET' }}"
          echo "RAPIDAPI_KEY_PROD: ${{ secrets.RAPIDAPI_KEY_PROD != '' && 'SET' || 'NOT SET' }}"
          echo "ABSTRACT_API_KEY_PROD: ${{ secrets.ABSTRACT_API_KEY_PROD != '' && 'SET' || 'NOT SET' }}"
          echo "SUPABASE_PROD_PROJECT_REF: ${{ secrets.SUPABASE_PROD_PROJECT_REF != '' && 'SET' || 'NOT SET' }}"
        else
          echo "SUPABASE_URL_DEV: ${{ secrets.SUPABASE_URL_DEV != '' && 'SET' || 'NOT SET' }}"
          echo "SUPABASE_SERVICE_ROLE_KEY_DEV: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_DEV != '' && 'SET' || 'NOT SET' }}"
          echo "OPENAI_API_KEY_DEV: ${{ secrets.OPENAI_API_KEY_DEV != '' && 'SET' || 'NOT SET' }}"
          echo "NEWSAPI_KEY_DEV: ${{ secrets.NEWSAPI_KEY_DEV != '' && 'SET' || 'NOT SET' }}"
          echo "SPORTSDB_API_KEY_DEV: ${{ secrets.SPORTSDB_API_KEY_DEV != '' && 'SET' || 'NOT SET' }}"
          echo "RAPIDAPI_KEY_DEV: ${{ secrets.RAPIDAPI_KEY_DEV != '' && 'SET' || 'NOT SET' }}"
          echo "ABSTRACT_API_KEY_DEV: ${{ secrets.ABSTRACT_API_KEY_DEV != '' && 'SET' || 'NOT SET' }}"
          echo "SUPABASE_DEV_PROJECT_REF: ${{ secrets.SUPABASE_DEV_PROJECT_REF != '' && 'SET' || 'NOT SET' }}"
        fi
        
        echo "✅ Secrets test completed" 